# Generated by Django 5.0.4 on 2024-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_carbody_carmodel_car_body_carmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='seats',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car_body',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(),
        ),
    ]
